version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - db_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - db_network
    volumes:
      - ./app:/usr/src/app

networks:
  db_network:
    driver: bridge