services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  app:
    image: node:latest
    command: sh -c "npm i && npm run watch"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb

volumes:
  mongodb_data: